experiment:
  name: bt-resnet18-stl10-to-stl10-benchmark
  seed: 42
  description: Official BarlowTwins ResNet18 pretrained on STL, benchmarked on STL10.

model:
  method: barlow_twins
  backbone: resnet18
  num_classes: 10
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  lamb: 0.0051
  scale_loss: 0.1
  backbone_args:
    zero_init_residual: true
#  optimizer: lars
#  max_epochs: 350
#  lr: 0.3
#  weight_decay: 1e-4
#  classifier_lr: 0.1

checkpoint:
  source:  solo_learn #official_repo # lub solo_learn
  path: ./project/models_out/checkpoints/mine/barlow_twins-stl10-7qzvnq5o-ep=341.ckpt #pytorch_hub # lub sciezka do wlasnego checkpointu w projekcie.
  hub_repo: null
  hub_model: null
  pretrain_dataset: stl10
  architecture: resnet18
  verified: true

outputs:
  embeddings_dir: ./project/models_out/embeddings
  report_dir: ./project/models_out/reports
  figures_dir: ./project/models_out/figures
  checkpoint_dir: ./project/models_out/checkpoints

benchmark:
  enabled: true

  dataset: stl10
  num_classes: 10

  data_dir: ./datasets/
  train_dir: null
  val_dir: null

  batch_size: 256 #2048
  num_workers: 4
  gpus: "0"

  use_projector: false

  preprocessing:
    type: custom # Zmiana z imagenet_eval na custom
    input_size: 96
    resize_size: 96
    normalization: cifar

  knn:
    k: 20
    temperature: 0.07
    distance_fx: cosine

  linear_eval:
    max_iter: 1000
    c: 1.0
    standardize: true

compression:
  enabled: false
  step_size: 50      # number of steps in for loop for removing additional dimentions
  add_projector: false #  performing phisical compression MLP?
  distilation: false

pretrain:
  enabled: false

finetune:
  enabled: false