# batch_size: 256 # Zwiększ do 2048-4096 dla ImageNet (wymaga dużej pamięci VRAM)
# lr: 0.3 # Skaluj liniowo: lr * (batch_size / 256)
# crop_size: 32 # Ustaw 224 dla ImageNet / ImageNet-100
# gaussian_blur: enabled: False # Włącz (True) tylko dla obrazów o wysokiej rozdzielczości (> 64px)

method: dino
dataset: cifar10
backbone: resnet50
num_classes: 10

name: dino-final-resnet50-cifar10

checkpoint: "pytorch_hub"
use_projector: false

backbone_args:
  zero_init_residual: true

proj_hidden_dim: 2048
proj_output_dim: 256
num_prototypes: 4096 # 65536 for ImageNet

student_temperature: 0.1
teacher_temperature: 0.04
warmup_teacher_temperature: 0.04
final_teacher_temperature: 0.07
warmup_teacher_temperature_epochs: 30

base_tau:  0.9995 #0.996
final_tau: 1.0
momentum_classifier: false

center_momentum: 0.9

max_epochs: 800
optimizer: lars #adamw
lr: 0.3 #0.002
weight_decay: 1e-6 #0.04
weight_decay_end: 0.4
classifier_lr: 0.5
accumulate_grad_batches: 1
extra_optimizer_args: {}

scheduler: warmup_cosine
scheduler_interval: step
min_lr: 0.0
warmup_start_lr: 0.0
warmup_epochs: 10
lr_decay_steps: null


augmentations:
  view1:
    rrc:
      enabled: True
      crop_size: #32
    gaussian_blur:
      prob: 1.0
  view2:
    rrc:
      enabled: True
      crop_size: 32
    gaussian_blur:
      prob: 0.1
    solarization:
      prob: 0.2

num_large_crops: 2
num_small_crops: 6
num_crops_per_aug: [1, 7]

batch_size: 1024
num_workers: 8
data_dir: ./datasets
train_dir: null
val_dir: null

gpus: "0"

# Ścieżki relatywne względem katalogu głównego
report_dir: project/models_out/reports
figures_dir: project/models_out/figures
embeddings_dir: project/models_out/embeddings
checkpoint_dir: project/models_out/checkpoints/mine

knn_k: 20
knn_temperature: 0.07
knn_distance_fx: cosine

linear_max_iter: 1000
linear_c: 1.0