experiment:
  name: dino-cifar10-student-resnet50-to-18
  seed: 42
  description: Distiled dino from Resnet50 to Resnet18 Imagenet to Cifar.

model:
  method: dino
  backbone: resnet18
  num_classes: 10
  proj_hidden_dim: 2048
  proj_output_dim: 256
  num_prototypes: 65536
  backbone_args:
    zero_init_residual: true
#  optimizer: lars
#  max_epochs: 100
#  lr: 0.3
#  weight_decay: 1e-4
#  classifier_lr: 0.1

checkpoint:
  source:  solo_learn #official_repo # lub solo_learn
  path: ./project/models_out/checkpoints/mine/dino_student_80epochs_stl_to_cifar.pth #pytorch_hub # lub sciezka do wlasnego checkpointu w projekcie.
  hub_repo: null
  hub_model: null
  pretrain_dataset: stl10
  architecture: resnet18
  verified: true

outputs:
  embeddings_dir: ./project/models_out/embeddings
  report_dir: ./project/models_out/reports
  figures_dir: ./project/models_out/figures
  checkpoint_dir: ./project/models_out/checkpoints

benchmark:
  enabled: true

  dataset: cifar10
  num_classes: 10

  data_dir: ./datasets/
  train_dir: null
  val_dir: null

  batch_size: 256
  num_workers: 4
  gpus: "0"

  use_projector: false

#  preprocessing:
#    type: custom
#    input_size: 32
#    resize_size: 32
#    normalization: cifar
  preprocessing:
    type: custom
    input_size: 224
    resize_size: 224


  knn:
    k: 20
    temperature: 0.07
    distance_fx: cosine

  linear_eval:
    max_iter: 1000
    c: 1.0
    standardize: true

compression:
  enabled: false
  step_size: 50      # number of steps in for loop for removing additional dimentions
  add_projector: false #  performing phisical compression MLP?
  distilation: false

pretrain:
  enabled: false

finetune:
  enabled: false