# batch_size: 256 # Zwiększ do 2048-4096 dla ImageNet (wymaga dużej pamięci VRAM)
# lr: 0.3 # Skaluj liniowo: lr * (batch_size / 256)
# crop_size: 32 # Ustaw 224 dla ImageNet / ImageNet-100
# gaussian_blur: enabled: False # Włącz (True) tylko dla obrazów o wysokiej rozdzielczości (> 64px)

method: vicreg
dataset: imagenet100
backbone: resnet50
num_classes: 100

name: vicreg-final-resnet50-imagenet100

checkpoint: "pytorch_hub"
use_projector: false

backbone_args:
  zero_init_residual: true

proj_hidden_dim: 8192
proj_output_dim: 8192

sim_loss_weight: 25.0
var_loss_weight: 25.0
cov_loss_weight: 1.0
eps: 0.0001

max_epochs: 1000
optimizer: lars #sgd
lars: true
lr:  0.3 #1.6
weight_decay: 1e-4 #0.000001
classifier_lr: 0.5
exclude_bias_n_norm_lars: true
accumulate_grad_batches: 1
extra_optimizer_args:
  momentum: 0.9

scheduler: warmup_cosine
scheduler_interval: step
min_lr: 0.002
warmup_start_lr: 0.0
warmup_epochs: 10
lr_decay_steps: null

augmentations:
  rrc:
    enabled: True
    crop_min_scale: 0.2 # Mniej agresywny crop dla 32x32[cite: 13]
    crop_size: 224
  color_jitter:
    prob: 0.8
  grayscale:
    prob: 0.2
  gaussian_blur:
    enabled: False # Wyłączono blur dla VICReg CIFAR[cite: 13] 0.5 dla image net
  solarization:
    prob: 0.1
  horizontal_flip:
    prob: 0.5


num_large_crops: 2
num_small_crops: 0
num_crops_per_aug: [2, 0]

batch_size:  256 #2048 dla ImageNet
num_workers: 8
data_dir: ./datasets/imagenet/
train_dir: ./datasets/imagenet/train
val_dir: ./datasets/imagenet/val

gpus: "0"

# Ścieżki relatywne względem katalogu głównego
report_dir: project/models_out/reports
figures_dir: project/models_out/figures
embeddings_dir: project/models_out/embeddings
checkpoint_dir: project/models_out/checkpoints/mine

knn_k: 20
knn_temperature: 0.1
knn_distance_fx: cosine

linear_max_iter: 1000
linear_c: 1.0